################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/MatrixFunctions.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/MatrixFunctionsF16.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_householder_f16.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_householder_f32.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_householder_f64.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_add_f16.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_add_f32.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_add_q15.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_add_q31.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cholesky_f16.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cholesky_f32.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cholesky_f64.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_mult_f16.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_mult_f32.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_mult_q15.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_mult_q31.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_trans_f16.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_trans_f32.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_trans_q15.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_trans_q31.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_init_f16.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_init_f32.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_init_f64.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_init_q15.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_init_q31.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_inverse_f16.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_inverse_f32.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_inverse_f64.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_ldlt_f32.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_ldlt_f64.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_f16.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_f32.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_f64.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_fast_q15.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_fast_q31.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_opt_q31.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_q15.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_q31.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_q7.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_qr_f16.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_qr_f32.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_qr_f64.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_scale_f16.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_scale_f32.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_scale_q15.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_scale_q31.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_lower_triangular_f16.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_lower_triangular_f32.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_lower_triangular_f64.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_upper_triangular_f16.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_upper_triangular_f32.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_upper_triangular_f64.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_sub_f16.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_sub_f32.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_sub_f64.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_sub_q15.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_sub_q31.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_f16.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_f32.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_f64.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_q15.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_q31.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_q7.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_vec_mult_f16.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_vec_mult_f32.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_vec_mult_q15.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_vec_mult_q31.c \
../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_vec_mult_q7.c 

C_DEPS += \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/MatrixFunctions.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/MatrixFunctionsF16.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_householder_f16.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_householder_f32.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_householder_f64.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_add_f16.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_add_f32.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_add_q15.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_add_q31.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cholesky_f16.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cholesky_f32.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cholesky_f64.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_mult_f16.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_mult_f32.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_mult_q15.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_mult_q31.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_trans_f16.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_trans_f32.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_trans_q15.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_trans_q31.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_init_f16.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_init_f32.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_init_f64.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_init_q15.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_init_q31.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_inverse_f16.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_inverse_f32.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_inverse_f64.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_ldlt_f32.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_ldlt_f64.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_f16.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_f32.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_f64.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_fast_q15.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_fast_q31.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_opt_q31.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_q15.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_q31.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_q7.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_qr_f16.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_qr_f32.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_qr_f64.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_scale_f16.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_scale_f32.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_scale_q15.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_scale_q31.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_lower_triangular_f16.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_lower_triangular_f32.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_lower_triangular_f64.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_upper_triangular_f16.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_upper_triangular_f32.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_upper_triangular_f64.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_sub_f16.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_sub_f32.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_sub_f64.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_sub_q15.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_sub_q31.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_f16.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_f32.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_f64.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_q15.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_q31.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_q7.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_vec_mult_f16.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_vec_mult_f32.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_vec_mult_q15.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_vec_mult_q31.d \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_vec_mult_q7.d 

OBJS += \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/MatrixFunctions.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/MatrixFunctionsF16.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_householder_f16.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_householder_f32.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_householder_f64.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_add_f16.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_add_f32.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_add_q15.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_add_q31.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cholesky_f16.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cholesky_f32.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cholesky_f64.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_mult_f16.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_mult_f32.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_mult_q15.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_mult_q31.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_trans_f16.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_trans_f32.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_trans_q15.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_trans_q31.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_init_f16.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_init_f32.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_init_f64.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_init_q15.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_init_q31.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_inverse_f16.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_inverse_f32.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_inverse_f64.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_ldlt_f32.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_ldlt_f64.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_f16.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_f32.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_f64.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_fast_q15.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_fast_q31.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_opt_q31.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_q15.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_q31.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_q7.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_qr_f16.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_qr_f32.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_qr_f64.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_scale_f16.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_scale_f32.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_scale_q15.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_scale_q31.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_lower_triangular_f16.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_lower_triangular_f32.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_lower_triangular_f64.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_upper_triangular_f16.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_upper_triangular_f32.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_upper_triangular_f64.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_sub_f16.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_sub_f32.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_sub_f64.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_sub_q15.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_sub_q31.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_f16.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_f32.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_f64.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_q15.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_q31.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_q7.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_vec_mult_f16.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_vec_mult_f32.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_vec_mult_q15.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_vec_mult_q31.o \
./CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_vec_mult_q7.o 

OBJS__QUOTED += \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\MatrixFunctions.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\MatrixFunctionsF16.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_householder_f16.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_householder_f32.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_householder_f64.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_add_f16.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_add_f32.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_add_q15.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_add_q31.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_cholesky_f16.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_cholesky_f32.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_cholesky_f64.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_cmplx_mult_f16.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_cmplx_mult_f32.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_cmplx_mult_q15.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_cmplx_mult_q31.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_cmplx_trans_f16.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_cmplx_trans_f32.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_cmplx_trans_q15.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_cmplx_trans_q31.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_init_f16.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_init_f32.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_init_f64.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_init_q15.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_init_q31.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_inverse_f16.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_inverse_f32.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_inverse_f64.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_ldlt_f32.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_ldlt_f64.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_mult_f16.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_mult_f32.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_mult_f64.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_mult_fast_q15.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_mult_fast_q31.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_mult_opt_q31.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_mult_q15.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_mult_q31.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_mult_q7.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_qr_f16.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_qr_f32.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_qr_f64.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_scale_f16.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_scale_f32.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_scale_q15.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_scale_q31.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_solve_lower_triangular_f16.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_solve_lower_triangular_f32.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_solve_lower_triangular_f64.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_solve_upper_triangular_f16.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_solve_upper_triangular_f32.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_solve_upper_triangular_f64.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_sub_f16.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_sub_f32.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_sub_f64.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_sub_q15.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_sub_q31.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_trans_f16.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_trans_f32.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_trans_f64.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_trans_q15.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_trans_q31.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_trans_q7.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_vec_mult_f16.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_vec_mult_f32.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_vec_mult_q15.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_vec_mult_q31.o" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_vec_mult_q7.o" 

C_DEPS__QUOTED += \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\MatrixFunctions.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\MatrixFunctionsF16.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_householder_f16.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_householder_f32.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_householder_f64.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_add_f16.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_add_f32.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_add_q15.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_add_q31.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_cholesky_f16.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_cholesky_f32.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_cholesky_f64.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_cmplx_mult_f16.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_cmplx_mult_f32.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_cmplx_mult_q15.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_cmplx_mult_q31.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_cmplx_trans_f16.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_cmplx_trans_f32.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_cmplx_trans_q15.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_cmplx_trans_q31.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_init_f16.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_init_f32.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_init_f64.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_init_q15.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_init_q31.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_inverse_f16.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_inverse_f32.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_inverse_f64.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_ldlt_f32.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_ldlt_f64.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_mult_f16.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_mult_f32.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_mult_f64.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_mult_fast_q15.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_mult_fast_q31.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_mult_opt_q31.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_mult_q15.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_mult_q31.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_mult_q7.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_qr_f16.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_qr_f32.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_qr_f64.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_scale_f16.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_scale_f32.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_scale_q15.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_scale_q31.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_solve_lower_triangular_f16.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_solve_lower_triangular_f32.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_solve_lower_triangular_f64.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_solve_upper_triangular_f16.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_solve_upper_triangular_f32.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_solve_upper_triangular_f64.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_sub_f16.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_sub_f32.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_sub_f64.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_sub_q15.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_sub_q31.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_trans_f16.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_trans_f32.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_trans_f64.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_trans_q15.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_trans_q31.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_trans_q7.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_vec_mult_f16.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_vec_mult_f32.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_vec_mult_q15.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_vec_mult_q31.d" \
"CMSIS-DSP.1.16.1\Source\MatrixFunctions\arm_mat_vec_mult_q7.d" 

C_SRCS__QUOTED += \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/MatrixFunctions.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/MatrixFunctionsF16.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_householder_f16.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_householder_f32.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_householder_f64.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_add_f16.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_add_f32.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_add_q15.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_add_q31.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cholesky_f16.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cholesky_f32.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cholesky_f64.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_mult_f16.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_mult_f32.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_mult_q15.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_mult_q31.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_trans_f16.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_trans_f32.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_trans_q15.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_cmplx_trans_q31.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_init_f16.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_init_f32.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_init_f64.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_init_q15.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_init_q31.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_inverse_f16.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_inverse_f32.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_inverse_f64.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_ldlt_f32.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_ldlt_f64.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_f16.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_f32.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_f64.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_fast_q15.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_fast_q31.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_opt_q31.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_q15.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_q31.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_mult_q7.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_qr_f16.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_qr_f32.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_qr_f64.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_scale_f16.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_scale_f32.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_scale_q15.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_scale_q31.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_lower_triangular_f16.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_lower_triangular_f32.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_lower_triangular_f64.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_upper_triangular_f16.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_upper_triangular_f32.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_solve_upper_triangular_f64.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_sub_f16.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_sub_f32.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_sub_f64.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_sub_q15.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_sub_q31.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_f16.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_f32.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_f64.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_q15.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_q31.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_trans_q7.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_vec_mult_f16.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_vec_mult_f32.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_vec_mult_q15.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_vec_mult_q31.c" \
"../CMSIS-DSP.1.16.1/Source/MatrixFunctions/arm_mat_vec_mult_q7.c" 


