################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/BasicMathFunctions.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/BasicMathFunctionsF16.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_f16.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_f32.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_f64.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_q15.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_q31.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_q7.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_f16.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_f32.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_f64.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_q15.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_q31.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_q7.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_and_u16.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_and_u32.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_and_u8.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_clip_f16.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_clip_f32.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_clip_q15.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_clip_q31.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_clip_q7.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_f16.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_f32.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_f64.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_q15.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_q31.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_q7.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_f16.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_f32.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_f64.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_q15.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_q31.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_q7.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_f16.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_f32.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_f64.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_q15.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_q31.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_q7.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_not_u16.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_not_u32.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_not_u8.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_f16.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_f32.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_f64.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_q15.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_q31.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_q7.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_or_u16.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_or_u32.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_or_u8.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_f16.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_f32.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_f64.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_q15.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_q31.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_q7.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_shift_q15.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_shift_q31.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_shift_q7.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_f16.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_f32.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_f64.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_q15.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_q31.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_q7.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_xor_u16.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_xor_u32.c \
../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_xor_u8.c 

C_DEPS += \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/BasicMathFunctions.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/BasicMathFunctionsF16.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_f16.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_f32.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_f64.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_q15.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_q31.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_q7.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_f16.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_f32.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_f64.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_q15.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_q31.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_q7.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_and_u16.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_and_u32.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_and_u8.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_clip_f16.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_clip_f32.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_clip_q15.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_clip_q31.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_clip_q7.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_f16.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_f32.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_f64.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_q15.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_q31.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_q7.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_f16.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_f32.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_f64.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_q15.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_q31.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_q7.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_f16.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_f32.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_f64.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_q15.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_q31.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_q7.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_not_u16.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_not_u32.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_not_u8.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_f16.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_f32.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_f64.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_q15.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_q31.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_q7.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_or_u16.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_or_u32.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_or_u8.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_f16.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_f32.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_f64.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_q15.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_q31.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_q7.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_shift_q15.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_shift_q31.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_shift_q7.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_f16.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_f32.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_f64.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_q15.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_q31.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_q7.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_xor_u16.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_xor_u32.d \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_xor_u8.d 

OBJS += \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/BasicMathFunctions.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/BasicMathFunctionsF16.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_f16.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_f32.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_f64.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_q15.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_q31.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_q7.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_f16.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_f32.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_f64.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_q15.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_q31.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_q7.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_and_u16.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_and_u32.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_and_u8.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_clip_f16.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_clip_f32.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_clip_q15.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_clip_q31.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_clip_q7.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_f16.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_f32.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_f64.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_q15.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_q31.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_q7.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_f16.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_f32.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_f64.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_q15.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_q31.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_q7.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_f16.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_f32.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_f64.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_q15.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_q31.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_q7.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_not_u16.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_not_u32.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_not_u8.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_f16.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_f32.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_f64.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_q15.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_q31.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_q7.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_or_u16.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_or_u32.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_or_u8.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_f16.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_f32.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_f64.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_q15.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_q31.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_q7.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_shift_q15.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_shift_q31.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_shift_q7.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_f16.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_f32.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_f64.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_q15.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_q31.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_q7.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_xor_u16.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_xor_u32.o \
./CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_xor_u8.o 

OBJS__QUOTED += \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\BasicMathFunctions.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\BasicMathFunctionsF16.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_abs_f16.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_abs_f32.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_abs_f64.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_abs_q15.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_abs_q31.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_abs_q7.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_add_f16.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_add_f32.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_add_f64.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_add_q15.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_add_q31.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_add_q7.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_and_u16.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_and_u32.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_and_u8.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_clip_f16.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_clip_f32.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_clip_q15.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_clip_q31.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_clip_q7.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_dot_prod_f16.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_dot_prod_f32.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_dot_prod_f64.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_dot_prod_q15.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_dot_prod_q31.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_dot_prod_q7.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_mult_f16.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_mult_f32.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_mult_f64.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_mult_q15.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_mult_q31.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_mult_q7.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_negate_f16.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_negate_f32.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_negate_f64.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_negate_q15.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_negate_q31.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_negate_q7.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_not_u16.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_not_u32.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_not_u8.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_offset_f16.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_offset_f32.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_offset_f64.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_offset_q15.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_offset_q31.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_offset_q7.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_or_u16.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_or_u32.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_or_u8.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_scale_f16.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_scale_f32.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_scale_f64.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_scale_q15.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_scale_q31.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_scale_q7.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_shift_q15.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_shift_q31.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_shift_q7.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_sub_f16.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_sub_f32.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_sub_f64.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_sub_q15.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_sub_q31.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_sub_q7.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_xor_u16.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_xor_u32.o" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_xor_u8.o" 

C_DEPS__QUOTED += \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\BasicMathFunctions.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\BasicMathFunctionsF16.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_abs_f16.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_abs_f32.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_abs_f64.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_abs_q15.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_abs_q31.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_abs_q7.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_add_f16.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_add_f32.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_add_f64.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_add_q15.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_add_q31.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_add_q7.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_and_u16.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_and_u32.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_and_u8.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_clip_f16.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_clip_f32.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_clip_q15.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_clip_q31.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_clip_q7.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_dot_prod_f16.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_dot_prod_f32.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_dot_prod_f64.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_dot_prod_q15.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_dot_prod_q31.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_dot_prod_q7.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_mult_f16.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_mult_f32.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_mult_f64.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_mult_q15.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_mult_q31.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_mult_q7.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_negate_f16.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_negate_f32.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_negate_f64.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_negate_q15.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_negate_q31.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_negate_q7.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_not_u16.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_not_u32.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_not_u8.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_offset_f16.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_offset_f32.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_offset_f64.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_offset_q15.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_offset_q31.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_offset_q7.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_or_u16.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_or_u32.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_or_u8.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_scale_f16.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_scale_f32.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_scale_f64.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_scale_q15.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_scale_q31.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_scale_q7.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_shift_q15.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_shift_q31.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_shift_q7.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_sub_f16.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_sub_f32.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_sub_f64.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_sub_q15.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_sub_q31.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_sub_q7.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_xor_u16.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_xor_u32.d" \
"CMSIS-DSP.1.16.1\Source\BasicMathFunctions\arm_xor_u8.d" 

C_SRCS__QUOTED += \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/BasicMathFunctions.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/BasicMathFunctionsF16.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_f16.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_f32.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_f64.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_q15.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_q31.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_abs_q7.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_f16.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_f32.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_f64.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_q15.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_q31.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_add_q7.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_and_u16.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_and_u32.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_and_u8.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_clip_f16.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_clip_f32.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_clip_q15.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_clip_q31.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_clip_q7.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_f16.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_f32.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_f64.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_q15.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_q31.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_dot_prod_q7.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_f16.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_f32.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_f64.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_q15.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_q31.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_mult_q7.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_f16.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_f32.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_f64.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_q15.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_q31.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_negate_q7.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_not_u16.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_not_u32.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_not_u8.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_f16.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_f32.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_f64.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_q15.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_q31.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_offset_q7.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_or_u16.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_or_u32.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_or_u8.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_f16.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_f32.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_f64.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_q15.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_q31.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_scale_q7.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_shift_q15.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_shift_q31.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_shift_q7.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_f16.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_f32.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_f64.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_q15.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_q31.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_sub_q7.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_xor_u16.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_xor_u32.c" \
"../CMSIS-DSP.1.16.1/Source/BasicMathFunctions/arm_xor_u8.c" 


