################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/TransformFunctions.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/TransformFunctionsF16.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_bitreversal.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_bitreversal2.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_bitreversal_f16.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_f16.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_f32.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_f64.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_init_f16.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_init_f32.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_init_f64.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_init_q15.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_init_q31.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_q15.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_q31.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_f16.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_f32.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_init_f16.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_init_f32.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_init_q15.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_init_q31.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_q15.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_q31.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_f16.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_f32.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_init_f16.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_init_f32.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_init_q15.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_init_q31.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_q15.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_q31.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix8_f16.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix8_f32.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_f32.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_init_f32.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_init_q15.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_init_q31.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_q15.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_q31.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_f16.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_f32.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_init_f16.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_init_f32.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_init_q15.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_init_q31.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_q15.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_q31.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_f32.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_f16.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_f32.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_f64.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_init_f16.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_init_f32.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_init_f64.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_init_f32.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_init_q15.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_init_q31.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_q15.c \
../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_q31.c 

C_DEPS += \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/TransformFunctions.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/TransformFunctionsF16.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_bitreversal.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_bitreversal2.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_bitreversal_f16.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_f16.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_f32.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_f64.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_init_f16.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_init_f32.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_init_f64.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_init_q15.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_init_q31.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_q15.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_q31.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_f16.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_f32.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_init_f16.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_init_f32.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_init_q15.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_init_q31.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_q15.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_q31.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_f16.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_f32.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_init_f16.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_init_f32.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_init_q15.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_init_q31.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_q15.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_q31.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix8_f16.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix8_f32.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_f32.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_init_f32.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_init_q15.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_init_q31.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_q15.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_q31.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_f16.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_f32.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_init_f16.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_init_f32.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_init_q15.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_init_q31.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_q15.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_q31.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_f32.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_f16.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_f32.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_f64.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_init_f16.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_init_f32.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_init_f64.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_init_f32.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_init_q15.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_init_q31.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_q15.d \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_q31.d 

OBJS += \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/TransformFunctions.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/TransformFunctionsF16.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_bitreversal.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_bitreversal2.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_bitreversal_f16.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_f16.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_f32.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_f64.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_init_f16.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_init_f32.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_init_f64.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_init_q15.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_init_q31.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_q15.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_q31.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_f16.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_f32.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_init_f16.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_init_f32.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_init_q15.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_init_q31.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_q15.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_q31.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_f16.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_f32.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_init_f16.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_init_f32.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_init_q15.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_init_q31.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_q15.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_q31.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix8_f16.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix8_f32.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_f32.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_init_f32.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_init_q15.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_init_q31.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_q15.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_q31.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_f16.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_f32.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_init_f16.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_init_f32.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_init_q15.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_init_q31.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_q15.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_q31.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_f32.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_f16.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_f32.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_f64.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_init_f16.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_init_f32.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_init_f64.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_init_f32.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_init_q15.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_init_q31.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_q15.o \
./CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_q31.o 

OBJS__QUOTED += \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\TransformFunctions.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\TransformFunctionsF16.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_bitreversal.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_bitreversal2.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_bitreversal_f16.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_f16.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_f32.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_f64.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_init_f16.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_init_f32.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_init_f64.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_init_q15.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_init_q31.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_q15.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_q31.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix2_f16.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix2_f32.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix2_init_f16.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix2_init_f32.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix2_init_q15.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix2_init_q31.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix2_q15.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix2_q31.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix4_f16.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix4_f32.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix4_init_f16.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix4_init_f32.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix4_init_q15.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix4_init_q31.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix4_q15.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix4_q31.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix8_f16.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix8_f32.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_dct4_f32.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_dct4_init_f32.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_dct4_init_q15.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_dct4_init_q31.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_dct4_q15.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_dct4_q31.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_mfcc_f16.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_mfcc_f32.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_mfcc_init_f16.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_mfcc_init_f32.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_mfcc_init_q15.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_mfcc_init_q31.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_mfcc_q15.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_mfcc_q31.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_f32.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_fast_f16.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_fast_f32.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_fast_f64.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_fast_init_f16.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_fast_init_f32.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_fast_init_f64.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_init_f32.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_init_q15.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_init_q31.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_q15.o" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_q31.o" 

C_DEPS__QUOTED += \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\TransformFunctions.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\TransformFunctionsF16.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_bitreversal.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_bitreversal2.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_bitreversal_f16.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_f16.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_f32.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_f64.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_init_f16.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_init_f32.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_init_f64.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_init_q15.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_init_q31.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_q15.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_q31.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix2_f16.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix2_f32.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix2_init_f16.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix2_init_f32.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix2_init_q15.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix2_init_q31.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix2_q15.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix2_q31.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix4_f16.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix4_f32.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix4_init_f16.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix4_init_f32.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix4_init_q15.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix4_init_q31.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix4_q15.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix4_q31.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix8_f16.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_cfft_radix8_f32.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_dct4_f32.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_dct4_init_f32.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_dct4_init_q15.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_dct4_init_q31.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_dct4_q15.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_dct4_q31.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_mfcc_f16.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_mfcc_f32.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_mfcc_init_f16.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_mfcc_init_f32.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_mfcc_init_q15.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_mfcc_init_q31.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_mfcc_q15.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_mfcc_q31.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_f32.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_fast_f16.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_fast_f32.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_fast_f64.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_fast_init_f16.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_fast_init_f32.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_fast_init_f64.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_init_f32.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_init_q15.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_init_q31.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_q15.d" \
"CMSIS-DSP.1.16.1\Source\TransformFunctions\arm_rfft_q31.d" 

C_SRCS__QUOTED += \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/TransformFunctions.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/TransformFunctionsF16.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_bitreversal.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_bitreversal2.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_bitreversal_f16.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_f16.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_f32.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_f64.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_init_f16.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_init_f32.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_init_f64.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_init_q15.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_init_q31.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_q15.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_q31.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_f16.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_f32.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_init_f16.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_init_f32.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_init_q15.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_init_q31.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_q15.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix2_q31.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_f16.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_f32.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_init_f16.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_init_f32.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_init_q15.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_init_q31.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_q15.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix4_q31.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix8_f16.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_cfft_radix8_f32.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_f32.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_init_f32.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_init_q15.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_init_q31.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_q15.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_dct4_q31.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_f16.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_f32.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_init_f16.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_init_f32.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_init_q15.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_init_q31.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_q15.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_mfcc_q31.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_f32.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_f16.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_f32.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_f64.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_init_f16.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_init_f32.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_fast_init_f64.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_init_f32.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_init_q15.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_init_q31.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_q15.c" \
"../CMSIS-DSP.1.16.1/Source/TransformFunctions/arm_rfft_q31.c" 


