################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/SupportFunctions.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/SupportFunctionsF16.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_barycenter_f16.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_barycenter_f32.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_bitonic_sort_f32.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_bubble_sort_f32.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_f16.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_f32.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_f64.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_q15.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_q31.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_q7.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f16_to_f64.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f16_to_float.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f16_to_q15.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f64_to_f16.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f64_to_float.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f64_to_q15.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f64_to_q31.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f64_to_q7.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_f16.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_f32.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_f64.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_q15.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_q31.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_q7.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_float_to_f16.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_float_to_f64.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_float_to_q15.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_float_to_q31.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_float_to_q7.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_heap_sort_f32.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_insertion_sort_f32.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_merge_sort_f32.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_merge_sort_init_f32.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q15_to_f16.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q15_to_f64.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q15_to_float.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q15_to_q31.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q15_to_q7.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q31_to_f64.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q31_to_float.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q31_to_q15.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q31_to_q7.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q7_to_f64.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q7_to_float.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q7_to_q15.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q7_to_q31.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_quick_sort_f32.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_selection_sort_f32.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_sort_f32.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_sort_init_f32.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_weighted_average_f16.c \
../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_weighted_average_f32.c 

C_DEPS += \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/SupportFunctions.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/SupportFunctionsF16.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_barycenter_f16.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_barycenter_f32.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_bitonic_sort_f32.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_bubble_sort_f32.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_f16.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_f32.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_f64.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_q15.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_q31.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_q7.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f16_to_f64.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f16_to_float.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f16_to_q15.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f64_to_f16.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f64_to_float.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f64_to_q15.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f64_to_q31.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f64_to_q7.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_f16.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_f32.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_f64.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_q15.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_q31.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_q7.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_float_to_f16.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_float_to_f64.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_float_to_q15.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_float_to_q31.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_float_to_q7.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_heap_sort_f32.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_insertion_sort_f32.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_merge_sort_f32.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_merge_sort_init_f32.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q15_to_f16.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q15_to_f64.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q15_to_float.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q15_to_q31.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q15_to_q7.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q31_to_f64.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q31_to_float.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q31_to_q15.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q31_to_q7.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q7_to_f64.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q7_to_float.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q7_to_q15.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q7_to_q31.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_quick_sort_f32.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_selection_sort_f32.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_sort_f32.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_sort_init_f32.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_weighted_average_f16.d \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_weighted_average_f32.d 

OBJS += \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/SupportFunctions.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/SupportFunctionsF16.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_barycenter_f16.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_barycenter_f32.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_bitonic_sort_f32.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_bubble_sort_f32.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_f16.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_f32.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_f64.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_q15.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_q31.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_q7.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f16_to_f64.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f16_to_float.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f16_to_q15.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f64_to_f16.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f64_to_float.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f64_to_q15.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f64_to_q31.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f64_to_q7.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_f16.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_f32.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_f64.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_q15.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_q31.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_q7.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_float_to_f16.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_float_to_f64.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_float_to_q15.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_float_to_q31.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_float_to_q7.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_heap_sort_f32.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_insertion_sort_f32.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_merge_sort_f32.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_merge_sort_init_f32.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q15_to_f16.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q15_to_f64.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q15_to_float.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q15_to_q31.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q15_to_q7.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q31_to_f64.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q31_to_float.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q31_to_q15.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q31_to_q7.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q7_to_f64.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q7_to_float.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q7_to_q15.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q7_to_q31.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_quick_sort_f32.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_selection_sort_f32.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_sort_f32.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_sort_init_f32.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_weighted_average_f16.o \
./CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_weighted_average_f32.o 

OBJS__QUOTED += \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\SupportFunctions.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\SupportFunctionsF16.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_barycenter_f16.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_barycenter_f32.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_bitonic_sort_f32.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_bubble_sort_f32.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_copy_f16.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_copy_f32.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_copy_f64.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_copy_q15.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_copy_q31.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_copy_q7.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_f16_to_f64.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_f16_to_float.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_f16_to_q15.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_f64_to_f16.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_f64_to_float.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_f64_to_q15.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_f64_to_q31.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_f64_to_q7.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_fill_f16.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_fill_f32.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_fill_f64.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_fill_q15.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_fill_q31.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_fill_q7.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_float_to_f16.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_float_to_f64.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_float_to_q15.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_float_to_q31.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_float_to_q7.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_heap_sort_f32.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_insertion_sort_f32.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_merge_sort_f32.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_merge_sort_init_f32.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q15_to_f16.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q15_to_f64.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q15_to_float.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q15_to_q31.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q15_to_q7.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q31_to_f64.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q31_to_float.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q31_to_q15.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q31_to_q7.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q7_to_f64.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q7_to_float.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q7_to_q15.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q7_to_q31.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_quick_sort_f32.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_selection_sort_f32.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_sort_f32.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_sort_init_f32.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_weighted_average_f16.o" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_weighted_average_f32.o" 

C_DEPS__QUOTED += \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\SupportFunctions.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\SupportFunctionsF16.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_barycenter_f16.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_barycenter_f32.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_bitonic_sort_f32.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_bubble_sort_f32.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_copy_f16.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_copy_f32.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_copy_f64.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_copy_q15.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_copy_q31.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_copy_q7.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_f16_to_f64.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_f16_to_float.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_f16_to_q15.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_f64_to_f16.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_f64_to_float.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_f64_to_q15.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_f64_to_q31.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_f64_to_q7.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_fill_f16.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_fill_f32.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_fill_f64.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_fill_q15.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_fill_q31.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_fill_q7.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_float_to_f16.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_float_to_f64.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_float_to_q15.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_float_to_q31.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_float_to_q7.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_heap_sort_f32.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_insertion_sort_f32.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_merge_sort_f32.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_merge_sort_init_f32.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q15_to_f16.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q15_to_f64.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q15_to_float.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q15_to_q31.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q15_to_q7.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q31_to_f64.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q31_to_float.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q31_to_q15.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q31_to_q7.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q7_to_f64.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q7_to_float.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q7_to_q15.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_q7_to_q31.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_quick_sort_f32.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_selection_sort_f32.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_sort_f32.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_sort_init_f32.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_weighted_average_f16.d" \
"CMSIS-DSP.1.16.1\Source\SupportFunctions\arm_weighted_average_f32.d" 

C_SRCS__QUOTED += \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/SupportFunctions.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/SupportFunctionsF16.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_barycenter_f16.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_barycenter_f32.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_bitonic_sort_f32.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_bubble_sort_f32.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_f16.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_f32.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_f64.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_q15.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_q31.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_copy_q7.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f16_to_f64.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f16_to_float.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f16_to_q15.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f64_to_f16.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f64_to_float.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f64_to_q15.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f64_to_q31.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_f64_to_q7.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_f16.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_f32.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_f64.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_q15.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_q31.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_fill_q7.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_float_to_f16.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_float_to_f64.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_float_to_q15.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_float_to_q31.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_float_to_q7.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_heap_sort_f32.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_insertion_sort_f32.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_merge_sort_f32.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_merge_sort_init_f32.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q15_to_f16.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q15_to_f64.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q15_to_float.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q15_to_q31.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q15_to_q7.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q31_to_f64.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q31_to_float.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q31_to_q15.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q31_to_q7.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q7_to_f64.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q7_to_float.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q7_to_q15.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_q7_to_q31.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_quick_sort_f32.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_selection_sort_f32.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_sort_f32.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_sort_init_f32.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_weighted_average_f16.c" \
"../CMSIS-DSP.1.16.1/Source/SupportFunctions/arm_weighted_average_f32.c" 


