################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/StatisticsFunctions.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/StatisticsFunctionsF16.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_f16.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_f32.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_f64.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_f16.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_f32.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_f64.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_q15.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_q31.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_q7.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_q15.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_q31.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_q7.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_f16.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_f32.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_f64.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_f16.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_f32.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_f64.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_q15.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_q31.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_q7.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_q15.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_q31.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_q7.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_accumulate_f16.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_accumulate_f32.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_accumulate_f64.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_entropy_f16.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_entropy_f32.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_entropy_f64.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_kullback_leibler_f16.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_kullback_leibler_f32.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_kullback_leibler_f64.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_logsumexp_f16.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_logsumexp_f32.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_f16.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_f32.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_f64.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_f16.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_f32.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_f64.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_q15.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_q31.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_q7.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_q15.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_q31.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_q7.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_f16.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_f32.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_f64.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_q15.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_q31.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_q7.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_f16.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_f32.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_f64.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_f16.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_f32.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_f64.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_q15.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_q31.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_q7.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_q15.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_q31.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_q7.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_f16.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_f32.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_f64.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_q15.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_q31.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_q7.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_f16.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_f32.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_f64.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_q15.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_q31.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_q7.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_rms_f16.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_rms_f32.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_rms_q15.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_rms_q31.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_std_f16.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_std_f32.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_std_f64.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_std_q15.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_std_q31.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_var_f16.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_var_f32.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_var_f64.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_var_q15.c \
../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_var_q31.c 

C_DEPS += \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/StatisticsFunctions.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/StatisticsFunctionsF16.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_f16.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_f32.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_f64.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_f16.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_f32.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_f64.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_q15.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_q31.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_q7.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_q15.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_q31.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_q7.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_f16.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_f32.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_f64.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_f16.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_f32.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_f64.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_q15.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_q31.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_q7.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_q15.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_q31.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_q7.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_accumulate_f16.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_accumulate_f32.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_accumulate_f64.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_entropy_f16.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_entropy_f32.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_entropy_f64.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_kullback_leibler_f16.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_kullback_leibler_f32.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_kullback_leibler_f64.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_logsumexp_f16.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_logsumexp_f32.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_f16.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_f32.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_f64.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_f16.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_f32.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_f64.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_q15.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_q31.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_q7.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_q15.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_q31.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_q7.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_f16.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_f32.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_f64.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_q15.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_q31.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_q7.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_f16.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_f32.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_f64.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_f16.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_f32.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_f64.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_q15.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_q31.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_q7.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_q15.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_q31.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_q7.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_f16.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_f32.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_f64.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_q15.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_q31.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_q7.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_f16.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_f32.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_f64.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_q15.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_q31.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_q7.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_rms_f16.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_rms_f32.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_rms_q15.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_rms_q31.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_std_f16.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_std_f32.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_std_f64.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_std_q15.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_std_q31.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_var_f16.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_var_f32.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_var_f64.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_var_q15.d \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_var_q31.d 

OBJS += \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/StatisticsFunctions.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/StatisticsFunctionsF16.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_f16.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_f32.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_f64.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_f16.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_f32.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_f64.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_q15.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_q31.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_q7.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_q15.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_q31.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_q7.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_f16.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_f32.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_f64.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_f16.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_f32.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_f64.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_q15.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_q31.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_q7.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_q15.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_q31.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_q7.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_accumulate_f16.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_accumulate_f32.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_accumulate_f64.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_entropy_f16.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_entropy_f32.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_entropy_f64.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_kullback_leibler_f16.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_kullback_leibler_f32.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_kullback_leibler_f64.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_logsumexp_f16.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_logsumexp_f32.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_f16.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_f32.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_f64.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_f16.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_f32.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_f64.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_q15.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_q31.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_q7.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_q15.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_q31.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_q7.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_f16.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_f32.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_f64.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_q15.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_q31.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_q7.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_f16.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_f32.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_f64.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_f16.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_f32.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_f64.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_q15.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_q31.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_q7.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_q15.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_q31.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_q7.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_f16.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_f32.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_f64.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_q15.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_q31.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_q7.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_f16.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_f32.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_f64.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_q15.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_q31.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_q7.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_rms_f16.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_rms_f32.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_rms_q15.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_rms_q31.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_std_f16.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_std_f32.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_std_f64.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_std_q15.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_std_q31.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_var_f16.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_var_f32.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_var_f64.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_var_q15.o \
./CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_var_q31.o 

OBJS__QUOTED += \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\StatisticsFunctions.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\StatisticsFunctionsF16.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_f16.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_f32.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_f64.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_no_idx_f16.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_no_idx_f32.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_no_idx_f64.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_no_idx_q15.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_no_idx_q31.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_no_idx_q7.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_q15.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_q31.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_q7.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_f16.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_f32.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_f64.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_no_idx_f16.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_no_idx_f32.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_no_idx_f64.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_no_idx_q15.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_no_idx_q31.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_no_idx_q7.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_q15.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_q31.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_q7.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_accumulate_f16.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_accumulate_f32.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_accumulate_f64.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_entropy_f16.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_entropy_f32.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_entropy_f64.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_kullback_leibler_f16.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_kullback_leibler_f32.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_kullback_leibler_f64.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_logsumexp_dot_prod_f16.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_logsumexp_dot_prod_f32.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_logsumexp_f16.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_logsumexp_f32.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_f16.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_f32.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_f64.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_no_idx_f16.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_no_idx_f32.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_no_idx_f64.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_no_idx_q15.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_no_idx_q31.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_no_idx_q7.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_q15.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_q31.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_q7.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mean_f16.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mean_f32.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mean_f64.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mean_q15.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mean_q31.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mean_q7.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_f16.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_f32.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_f64.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_no_idx_f16.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_no_idx_f32.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_no_idx_f64.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_no_idx_q15.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_no_idx_q31.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_no_idx_q7.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_q15.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_q31.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_q7.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mse_f16.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mse_f32.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mse_f64.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mse_q15.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mse_q31.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mse_q7.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_power_f16.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_power_f32.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_power_f64.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_power_q15.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_power_q31.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_power_q7.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_rms_f16.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_rms_f32.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_rms_q15.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_rms_q31.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_std_f16.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_std_f32.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_std_f64.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_std_q15.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_std_q31.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_var_f16.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_var_f32.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_var_f64.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_var_q15.o" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_var_q31.o" 

C_DEPS__QUOTED += \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\StatisticsFunctions.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\StatisticsFunctionsF16.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_f16.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_f32.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_f64.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_no_idx_f16.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_no_idx_f32.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_no_idx_f64.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_no_idx_q15.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_no_idx_q31.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_no_idx_q7.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_q15.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_q31.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmax_q7.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_f16.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_f32.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_f64.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_no_idx_f16.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_no_idx_f32.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_no_idx_f64.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_no_idx_q15.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_no_idx_q31.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_no_idx_q7.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_q15.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_q31.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_absmin_q7.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_accumulate_f16.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_accumulate_f32.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_accumulate_f64.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_entropy_f16.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_entropy_f32.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_entropy_f64.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_kullback_leibler_f16.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_kullback_leibler_f32.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_kullback_leibler_f64.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_logsumexp_dot_prod_f16.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_logsumexp_dot_prod_f32.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_logsumexp_f16.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_logsumexp_f32.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_f16.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_f32.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_f64.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_no_idx_f16.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_no_idx_f32.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_no_idx_f64.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_no_idx_q15.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_no_idx_q31.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_no_idx_q7.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_q15.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_q31.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_max_q7.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mean_f16.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mean_f32.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mean_f64.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mean_q15.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mean_q31.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mean_q7.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_f16.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_f32.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_f64.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_no_idx_f16.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_no_idx_f32.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_no_idx_f64.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_no_idx_q15.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_no_idx_q31.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_no_idx_q7.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_q15.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_q31.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_min_q7.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mse_f16.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mse_f32.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mse_f64.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mse_q15.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mse_q31.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_mse_q7.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_power_f16.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_power_f32.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_power_f64.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_power_q15.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_power_q31.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_power_q7.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_rms_f16.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_rms_f32.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_rms_q15.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_rms_q31.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_std_f16.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_std_f32.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_std_f64.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_std_q15.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_std_q31.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_var_f16.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_var_f32.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_var_f64.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_var_q15.d" \
"CMSIS-DSP.1.16.1\Source\StatisticsFunctions\arm_var_q31.d" 

C_SRCS__QUOTED += \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/StatisticsFunctions.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/StatisticsFunctionsF16.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_f16.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_f32.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_f64.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_f16.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_f32.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_f64.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_q15.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_q31.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_no_idx_q7.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_q15.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_q31.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmax_q7.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_f16.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_f32.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_f64.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_f16.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_f32.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_f64.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_q15.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_q31.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_no_idx_q7.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_q15.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_q31.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_absmin_q7.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_accumulate_f16.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_accumulate_f32.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_accumulate_f64.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_entropy_f16.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_entropy_f32.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_entropy_f64.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_kullback_leibler_f16.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_kullback_leibler_f32.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_kullback_leibler_f64.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f16.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_logsumexp_dot_prod_f32.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_logsumexp_f16.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_logsumexp_f32.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_f16.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_f32.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_f64.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_f16.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_f32.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_f64.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_q15.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_q31.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_no_idx_q7.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_q15.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_q31.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_max_q7.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_f16.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_f32.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_f64.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_q15.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_q31.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mean_q7.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_f16.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_f32.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_f64.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_f16.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_f32.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_f64.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_q15.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_q31.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_no_idx_q7.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_q15.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_q31.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_min_q7.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_f16.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_f32.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_f64.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_q15.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_q31.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_mse_q7.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_f16.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_f32.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_f64.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_q15.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_q31.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_power_q7.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_rms_f16.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_rms_f32.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_rms_q15.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_rms_q31.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_std_f16.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_std_f32.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_std_f64.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_std_q15.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_std_q31.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_var_f16.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_var_f32.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_var_f64.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_var_q15.c" \
"../CMSIS-DSP.1.16.1/Source/StatisticsFunctions/arm_var_q31.c" 


